In [28]:
import pandas
data = pandas.read_csv('data.csv')
print(type(data), '\n')
print(data.dtypes, '\n')
print(help(pandas.read_csv))

<class 'pandas.core.frame.DataFrame'>

Reporting Week                int64
Sail Year                     int64
Sail Month                    int64
F Pol Dep Time Id             int64
L Pod Arr Time Id             int64
Primary Svvd Close Date     float64
Cgo Trade Cde                object
Cgo Trade Lane Cde           object
Shipment DIR                 object
BPM Sales Region             object
BPM Sales Ofce Cde           object
BPM Local Region             object
Orig Ofce Cde                object
Primary Svvd Id              object
F Base Pol Svvd              object
L Base Pod Svvd              object
F Pol Svvd                   object
L Pod Svvd                   object
Trckg Grp Ref Cde             int64
Bl Ref Cde                    int64
Sc Num                       object
AGMT NUM                     object
Agreement Creator            object
Agreement Approver           object
TEU                           int64
Freight Revenue             float64
Orig City Nme                object
Orig State                   object
Orig Country Nme             object
Dest City Nme                object
                             ...
BOUND                        object
Contrib1                    float64
Contrib2                    float64
Contrib3                    float64
Net Freight                 float64
Cust ID                       int64
Cust Main Name               object
SOC IND                       int64
Intra river Ind               int64
Trade Division               object
Booking Party Code            int64
Booking Party Name           object
Dest Region                  object
Booking Office               object
Account Scale                object
BCO_NVO                      object
Industry                     object
FOB IND                       int64
CNTR TYPE GRP                object
Region GRP Main Nme          object
GBL Grp Main Nme             object
BPM Sales Country            object
F_POL_DEP_TIME_ID             int64
INLAND_CGO_ID                 int64
SC_COMMODITY_GROUP           object
C3 Adjustment               float64
Dest Office                  object
Commodity Group              object
品名                           object
Primary SVVD Season Type     object
Length: 80, dtype: object

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read CSV (comma-separated) file into DataFrame

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the `online docs for IO Tools
    <http://pandas.pydata.org/pandas-docs/stable/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, pathlib.Path, py._path.local.LocalPath or any \
    object with a read() method (such as a file handle or StringIO)
        The string could be a URL. Valid URL schemes include http, ftp, s3, and
        file. For file URLs, a host is expected. For instance, a local file could
        be file://localhost/path/to/table.csv
    sep : str, default ','
        Delimiter to use. If sep is None, the C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator by Python's builtin sniffer
        tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
        different from ``'\s+'`` will be interpreted as regular expressions and
        will also force the use of the Python parsing engine. Note that regex
        delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``
    delimiter : str, default ``None``
        Alternative argument name for sep.
    delim_whitespace : boolean, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be
        used as the sep. Equivalent to setting ``sep='\s+'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.

        .. versionadded:: 0.18.1 support for the Python parser.

    header : int or list of ints, default 'infer'
        Row number(s) to use as the column names, and the start of the
        data.  Default behavior is to infer the column names: if no names
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a multi-index on the columns
        e.g. [0,1,3]. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so header=0 denotes the first line of
        data rather than the first line of the file.
    names : array-like, default None
        List of column names to use. If file contains no header row, then you
        should explicitly pass header=None. Duplicates in this list will cause
        a ``UserWarning`` to be issued.
    index_col : int or sequence or False, default None
        Column to use as the row labels of the DataFrame. If a sequence is given, a
        MultiIndex is used. If you have a malformed file with delimiters at the end
        of each line, you might consider index_col=False to force pandas to _not_
        use the first column as the index (row names)
    usecols : list-like or callable, default None
        Return a subset of the columns. If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). For example, a valid list-like
        `usecols` parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Element
        order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a DataFrame from ``data`` with element order preserved use
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
        in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to True. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    squeeze : boolean, default False
        If the parsed data only contains one column then return a Series
    prefix : str, default None
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
    mangle_dupe_cols : boolean, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use `str` or `object` together with suitable `na_values` settings
        to preserve and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : {'c', 'python'}, optional
        Parser engine to use. The C engine is faster while the python engine is
        currently more feature-complete.
    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels
    true_values : list, default None
        Values to consider as True
    false_values : list, default None
        Values to consider as False
    skipinitialspace : boolean, default False
        Skip spaces after delimiter.
    skiprows : list-like or integer or callable, default None
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning True if the row should be skipped and False otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c')
    nrows : int, default None
        Number of rows of file to read. Useful for reading pieces of large files
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
        'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : boolean, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file
    verbose : boolean, default False
        Indicate number of NA values placed in non-numeric columns
    skip_blank_lines : boolean, default True
        If True, skip over blank lines rather than interpreting as NaN values
    parse_dates : boolean or list of ints or names or list of lists or dict, default False

        * boolean. If True -> try parsing the index.
        * list of ints or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call result
          'foo'

        If a column or index contains an unparseable date, the entire column or
        index will be returned unaltered as an object data type. For non-standard
        datetime parsing, use ``pd.to_datetime`` after ``pd.read_csv``

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : boolean, default False
        If True and `parse_dates` is enabled, pandas will attempt to infer the
        format of the datetime strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.
    keep_date_col : boolean, default False
        If True and `parse_dates` specifies combining multiple columns then
        keep the original columns.
    date_parser : function, default None
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    dayfirst : boolean, default False
        DD/MM format dates, international and European format
    iterator : boolean, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, default None
        Return TextFileReader object for iteration.
        See the `IO Tools docs
        <http://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.
    compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and
        `filepath_or_buffer` is path-like, then detect compression from the
        following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
        decompression). If using 'zip', the ZIP file must contain only one data
        file to be read in. Set to None for no decompression.

        .. versionadded:: 0.18.1 support for 'zip' and 'xz' compression.

    thousands : str, default None
        Thousands separator
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    float_precision : string, default None
        Specifies which converter the C engine should use for floating-point
        values. The options are `None` for the ordinary converter,
        `high` for the high-precision converter, and `round_trip` for the
        round-trip converter.
    lineterminator : str (length 1), default None
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default 0
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
    doublequote : boolean, default ``True``
       When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive quotechar elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), default None
        One-character string used to escape delimiter when quoting is QUOTE_NONE.
    comment : str, default None
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
        treated as the header.
    encoding : str, default None
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_
    dialect : str or csv.Dialect instance, default None
        If provided, this parameter will override values (default or not) for the
        following parameters: `delimiter`, `doublequote`, `escapechar`,
        `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
        override values, a ParserWarning will be issued. See csv.Dialect
        documentation for more details.
    tupleize_cols : boolean, default False
        .. deprecated:: 0.21.0
           This argument will be removed and will always convert to MultiIndex

        Leave a list of tuples on columns as is (default is to convert to
        a MultiIndex on the columns)
    error_bad_lines : boolean, default True
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will dropped from the DataFrame that is
        returned.
    warn_bad_lines : boolean, default True
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output.
    low_memory : boolean, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set False, or specify the type with the `dtype` parameter.
        Note that the entire file is read into a single DataFrame regardless,
        use the `chunksize` or `iterator` parameter to return the data in chunks.
        (Only valid with C parser)
    memory_map : boolean, default False
        If a filepath is provided for `filepath_or_buffer`, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.

    Returns
    -------
    result : DataFrame or TextParser

None

In [ ]:
import csv
with open('data.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in reader:
        print(row)
        print(row, '\n')

In [12]:
# data.head(3)
# first_rows = data.head()
# print(first_rows)
# data.tail(4)
# print(data.tail(3))
# print(data.columns)
print(data.shape)

(2399, 80)

In [11]:
# object - For string values
# int - For integer values
# float - For float values
# datetime - For time values
# bool - For Boolean values
# print(data.dtypes)

In [19]:
# Returns a DataFrame containing the rows at indexes 3, 4, 5, and 6.
# data.loc[3:6]

# Returns a Data Frame containing the rows at indexes 2, 5, and 10.
# Method 1
# two_five_ten = [2, 5, 10]
# data.loc[two_five_ten]

# Method 2
# data.loc[[2, 5, 10]]

,Reporting Week,Sail Year,Sail Month,F Pol Dep Time Id,L Pod Arr Time Id,Primary Svvd Close Date,Cgo Trade Cde,Cgo Trade Lane Cde,Shipment DIR,BPM Sales Region,...,GBL Grp Main Nme,BPM Sales Country,F_POL_DEP_TIME_ID,INLAND_CGO_ID,SC_COMMODITY_GROUP,C3 Adjustment,Dest Office,Commodity Group,品名,Primary SVVD Season Type
2,201701,2017,1,20170101,20160105,20170101.0,ICT,ICT,S,B.XMN,...,NaN,China,20170101,1,NaN,108.79,ZUH,NaN,NaN,NaN
5,201701,2017,1,20170101,20161223,20170101.0,IAT,IAA,N,C.Asia(SE),...,NaN,Indonesia,20170101,0,NaN,25.94,KUL,OTH,其他,NaN
10,201701,2017,1,20170101,20161223,20170101.0,IAT,IAA,N,C.Asia(SE),...,NaN,Indonesia,20170101,0,NaN,457.56,KUL,NaN,NaN,NaN

In [22]:
# Series object representing the 'C3 Adjustment' column.
# name = data['C3 Adjustment']
# print(name)
# Alternatively, you can access a column by passing in a string variable.
# col_name = 'C3 Adjustment'
# name = data[col_name]
# print(name)

In [23]:
columns = ['BPM Sales Country', 'C3 Adjustment']
zinc_copper = data[columns]
print(zinc_copper)

     BPM Sales Country  C3 Adjustment
0                China         278.22
1                China          28.77
2                China         108.79
3                China          26.58
4                China         291.05
5            Indonesia          25.94
6            Indonesia         181.58
7            Indonesia         674.16
8            Indonesia        1715.85
9            Indonesia         155.64
10           Indonesia         457.56
11           Indonesia         114.39
12           Indonesia          51.88
13           Indonesia         114.39
14           Indonesia          12.97
15           Indonesia          25.94
16           Indonesia         228.78
17           Indonesia          25.94
18        Saudi Arabia         153.79
19        Saudi Arabia         562.00
20              Turkey         478.88
21              Turkey         485.00
22              Greece         807.07
23               China        1169.27
24               China        1128.10
25               China         589.43
26               China         415.12
27        Head Quarter         475.27
28               China        2160.44
29               China        1296.26
...                ...            ...
2369             China         124.08
2370             China         439.99
2371             China        -430.27
2372             China          49.96
2373             China         110.53
2374             China         293.52
2375             China          10.19
2376             China         100.94
2377             China          81.99
2378             China         100.95
2379             China         163.98
2380             China         109.44
2381             China         192.18
2382             China         130.40
2383             China         130.40
2384             China         130.40
2385             China         397.53
2386             China         198.77
2387             China         320.81
2388             China         184.40
2389             China         306.30
2390             China         641.20
2391             China        1614.10
2392             China         334.38
2393             China         367.01
2394             China         293.11
2395             China        1121.72
2396             China         731.82
2397             China         575.04
2398             China         575.04

[2399 rows x 2 columns]

In [24]:
print(data.columns)
# print(data.head(3))
col_names = data.columns.tolist()
print(col_names)

Index(['Reporting Week', 'Sail Year', 'Sail Month', 'F Pol Dep Time Id',
       'L Pod Arr Time Id', 'Primary Svvd Close Date', 'Cgo Trade Cde',
       'Cgo Trade Lane Cde', 'Shipment DIR', 'BPM Sales Region',
       'BPM Sales Ofce Cde', 'BPM Local Region', 'Orig Ofce Cde',
       'Primary Svvd Id', 'F Base Pol Svvd', 'L Base Pod Svvd', 'F Pol Svvd',
       'L Pod Svvd', 'Trckg Grp Ref Cde', 'Bl Ref Cde', 'Sc Num', 'AGMT NUM',
       'Agreement Creator', 'Agreement Approver', 'TEU', 'Freight Revenue',
       'Orig City Nme', 'Orig State', 'Orig Country Nme', 'Dest City Nme',
       'Dest State', 'Dest Country Nme', 'F Pol Nme', 'L Pod Nme',
       'F Base Pol Nme', 'L Base Pod Nme', 'Cntr Type', 'Cgo Nature Cde',
       'Sales Rep Code', 'Sales Name', 'SCTD IND', 'Freight  Revenue Type',
       'Shipper Cde', 'Shipper Nme', 'Consign Cde', 'Consign Nme',
       'Forward Cde', 'Forward Name', 'Ctrct Ctrl Pty Cde',
       'Ctrct Ctrl Pty Name', 'BOUND', 'Contrib1', 'Contrib2', 'Contrib3',
       'Net Freight', 'Cust ID', 'Cust Main Name', 'SOC IND',
       'Intra river Ind', 'Trade Division', 'Booking Party Code',
       'Booking Party Name', 'Dest Region', 'Booking Office', 'Account Scale',
       'BCO_NVO', 'Industry', 'FOB IND', 'CNTR TYPE GRP',
       'Region GRP Main Nme', 'GBL Grp Main Nme', 'BPM Sales Country',
       'F_POL_DEP_TIME_ID', 'INLAND_CGO_ID', 'SC_COMMODITY_GROUP',
       'C3 Adjustment', 'Dest Office', 'Commodity Group', '品名',
       'Primary SVVD Season Type'],
      dtype='object')
['Reporting Week', 'Sail Year', 'Sail Month', 'F Pol Dep Time Id', 'L Pod Arr Time Id', 'Primary Svvd Close Date', 'Cgo Trade Cde', 'Cgo Trade Lane Cde', 'Shipment DIR', 'BPM Sales Region', 'BPM Sales Ofce Cde', 'BPM Local Region', 'Orig Ofce Cde', 'Primary Svvd Id', 'F Base Pol Svvd', 'L Base Pod Svvd', 'F Pol Svvd', 'L Pod Svvd', 'Trckg Grp Ref Cde', 'Bl Ref Cde', 'Sc Num', 'AGMT NUM', 'Agreement Creator', 'Agreement Approver', 'TEU', 'Freight Revenue', 'Orig City Nme', 'Orig State', 'Orig Country Nme', 'Dest City Nme', 'Dest State', 'Dest Country Nme', 'F Pol Nme', 'L Pod Nme', 'F Base Pol Nme', 'L Base Pod Nme', 'Cntr Type', 'Cgo Nature Cde', 'Sales Rep Code', 'Sales Name', 'SCTD IND', 'Freight  Revenue Type', 'Shipper Cde', 'Shipper Nme', 'Consign Cde', 'Consign Nme', 'Forward Cde', 'Forward Name', 'Ctrct Ctrl Pty Cde', 'Ctrct Ctrl Pty Name', 'BOUND', 'Contrib1', 'Contrib2', 'Contrib3', 'Net Freight', 'Cust ID', 'Cust Main Name', 'SOC IND', 'Intra river Ind', 'Trade Division', 'Booking Party Code', 'Booking Party Name', 'Dest Region', 'Booking Office', 'Account Scale', 'BCO_NVO', 'Industry', 'FOB IND', 'CNTR TYPE GRP', 'Region GRP Main Nme', 'GBL Grp Main Nme', 'BPM Sales Country', 'F_POL_DEP_TIME_ID', 'INLAND_CGO_ID', 'SC_COMMODITY_GROUP', 'C3 Adjustment', 'Dest Office', 'Commodity Group', '品名', 'Primary SVVD Season Type']

In [35]:
CA_max = data['C3 Adjustment'].max()
CA_min = data['C3 Adjustment'].min()
dis = CA_max - CA_min
CA_new = data['C3 Adjustment']/dis
print(CA_new)

0       0.010738
1       0.001110
2       0.004199
3       0.001026
4       0.011233
5       0.001001
6       0.007008
7       0.026020
8       0.066224
9       0.006007
10      0.017660
11      0.004415
12      0.002002
13      0.004415
14      0.000501
15      0.001001
16      0.008830
17      0.001001
18      0.005936
19      0.021691
20      0.018483
21      0.018719
22      0.031149
23      0.045129
24      0.043540
25      0.022749
26      0.016022
27      0.018343
28      0.083383
29      0.050030
          ...
2369    0.004789
2370    0.016982
2371   -0.016607
2372    0.001928
2373    0.004266
2374    0.011329
2375    0.000393
2376    0.003896
2377    0.003164
2378    0.003896
2379    0.006329
2380    0.004224
2381    0.007417
2382    0.005033
2383    0.005033
2384    0.005033
2385    0.015343
2386    0.007672
2387    0.012382
2388    0.007117
2389    0.011822
2390    0.024747
2391    0.062297
2392    0.012906
2393    0.014165
2394    0.011313
2395    0.043293
2396    0.028245
2397    0.022194
2398    0.022194
Name: C3 Adjustment, Length: 2399, dtype: float64

In [26]:
# Sorts the DataFrame in-place, rather than=true returning a new DataFrame
# data.sort_values('C3 Adjustment', inplace=True)
# print(data['C3 Adjustment'])
# Sorts by descending order, rather than ascending.
data.sort_values('C3 Adjustment', inplace=True, ascending=False)
print(data['C3 Adjustment'])

956     12509.82
32      11825.91
580     11098.14
470      8814.10
721      6714.29
1360     5814.10
1033     5629.89
2010     5629.61
1181     5415.06
206      4999.74
579      4932.50
1205     4558.53
581      4503.52
2078     4489.03
191      4405.95
1203     3976.59
631      3699.38
1020     3689.62
1248     3649.38
1249     3649.38
1273     3633.59
576      3531.58
616      3336.52
1044     3152.75
463      3146.38
1243     3110.39
1202     3103.68
602      3053.32
1095     3049.92
184      3027.89
          ...
2184     -169.55
2132     -182.43
767      -184.16
2188     -187.55
2192     -187.55
2187     -187.55
2191     -187.55
2255     -196.62
973      -248.72
2131     -272.44
1926     -273.84
2145     -276.65
2190     -284.80
2186     -309.10
2185     -309.10
2183     -309.10
2371     -430.27
1975     -455.76
1974     -455.76
1947     -461.70
975      -464.48
2195     -490.59
2358     -628.15
2196     -676.30
2252     -887.83
2357    -1130.71
2136    -1322.53
2135    -3422.76
573    -13399.87
572    -13399.87
Name: C3 Adjustment, Length: 2399, dtype: float64

In [40]:
CA = data['C3 Adjustment']
is_null = pandas.isnull(CA)
null_true = CA[is_null]

In [43]:
# missing data is so common that many pandas methods automatically filter for it
ca_avg = sum(CA)/len(CA)
print(ca_avg)

415.4335014589418

In [44]:
import numpy as np

In [ ]:
# index tells the method which column to group by
# values is the column that we want to apply the calculation to
# aggfunc specifies the calculation we want to perform
passenger_survival = titanic_survival.pivot_table(index='Pclass', values='Survived', aggfunc=np.mean)
print(passenget_survival)

Pclass
1     0.629630
2     0.472826
3     0.242363
Name: Survived, dtype: float64

In [ ]:
passenger_age = titanic_survival.pivot_table(index='Pclass', values='age')
print(passenger_age)

Pclass
1     38.233441
2     29.877630
3     25.140620
Name: Survived, dtype: float64

In [ ]:
port_stats = titanic_survival.pivot_table(index='Embarked', values=['Fare', 'Survived'], aggfunc=np.sum)
print(port_stats)

        Fare    Survived
Embarked
C       10072     93
Q       1022      30
S       17439     217

In [ ]:
# specifyting axis=1 or axis='columns' will drop any columns that have null values
drop_na_columns = titanic_survival.dropna(axis=1)
new_titanic_survival = titanic_survival.dropna(axis=0, subset=['Age', 'Sex'])
print(new_titanic_survival)

In [63]:
print(data.dropna(axis=1))
# print(data)

      Reporting Week  Sail Year  Sail Month  F Pol Dep Time Id  \
0             201701       2017           1           20170101
1             201701       2017           1           20170101
2             201701       2017           1           20170101
3             201701       2017           1           20170101
4             201701       2017           1           20170101
5             201701       2017           1           20170101
6             201701       2017           1           20170101
7             201701       2017           1           20170101
8             201701       2017           1           20170101
9             201701       2017           1           20170101
10            201701       2017           1           20170101
11            201701       2017           1           20170101
12            201701       2017           1           20170101
13            201701       2017           1           20170101
14            201701       2017           1           20170101
15            201701       2017           1           20170101
16            201701       2017           1           20170101
17            201701       2017           1           20170101
18            201701       2017           1           20170101
19            201701       2017           1           20170101
20            201701       2017           1           20170101
21            201701       2017           1           20170101
22            201701       2017           1           20170101
23            201701       2017           1           20170101
24            201701       2017           1           20170101
25            201701       2017           1           20170101
26            201701       2017           1           20170101
27            201701       2017           1           20170101
28            201701       2017           1           20170101
29            201701       2017           1           20170101
...              ...        ...         ...                ...
2369          201701       2017           1           20170101
2370          201701       2017           1           20170101
2371          201701       2017           1           20170101
2372          201701       2017           1           20170101
2373          201701       2017           1           20170101
2374          201701       2017           1           20170101
2375          201701       2017           1           20170101
2376          201701       2017           1           20170101
2377          201701       2017           1           20170101
2378          201701       2017           1           20170101
2379          201701       2017           1           20170101
2380          201701       2017           1           20170101
2381          201701       2017           1           20170101
2382          201701       2017           1           20170101
2383          201701       2017           1           20170101
2384          201701       2017           1           20170101
2385          201701       2017           1           20170101
2386          201701       2017           1           20170101
2387          201701       2017           1           20170101
2388          201701       2017           1           20170101
2389          201701       2017           1           20170101
2390          201701       2017           1           20170101
2391          201701       2017           1           20170101
2392          201701       2017           1           20170101
2393          201701       2017           1           20170101
2394          201701       2017           1           20170101
2395          201701       2017           1           20170101
2396          201701       2017           1           20170101
2397          201701       2017           1           20170101
2398          201701       2017           1           20170101

      L Pod Arr Time Id Cgo Trade Cde Cgo Trade Lane Cde BPM Sales Region  \
0              20160105           ICT                ICT            B.XMN
1              20160105           ICT                ICT            B.XMN
2              20160105           ICT                ICT            B.XMN
3              20160105           ICT                ICT            B.XMN
4              20161211           ICT                ICT            B.DLC
5              20161223           IAT                IAA       C.Asia(SE)
6              20161223           IAT                IAA       C.Asia(SE)
7              20161223           IAT                IAA       C.Asia(SE)
8              20161223           IAT                IAA       C.Asia(SE)
9              20161223           IAT                IAA       C.Asia(SE)
10             20161223           IAT                IAA       C.Asia(SE)
11             20161223           IAT                IAA       C.Asia(SE)
12             20161223           IAT                IAA       C.Asia(SE)
13             20161223           IAT                IAA       C.Asia(SE)
14             20161223           IAT                IAA       C.Asia(SE)
15             20161223           IAT                IAA       C.Asia(SE)
16             20161223           IAT                IAA       C.Asia(SE)
17             20161223           IAT                IAA       C.Asia(SE)
18             20161226           IAT                IAR        B.Asia(W)
19             20161226           IAT                IAR        B.Asia(W)
20             20161228           IET                IET         C.Europe
21             20161228           IET                IET         C.Europe
22             20161228           IET                IET         C.Europe
23             20161230           ICT                ICT            B.DLC
24             20161230           ICT                ICT            B.DLC
25             20161230           ICT                ICT            B.DLC
26             20161230           ICT                ICT            B.DLC
27             20161230           ICT                ICT            B.HQR
28             20161230           ICT                ICT            B.WUH
29             20161230           ICT                ICT            B.WUH
...                 ...           ...                ...              ...
2369           20170107           ICT                ICT            B.NGB
2370           20170107           ICT                ICT            B.NGB
2371           20170107           ICT                ICT            B.NGB
2372           20170107           ICT                ICT            B.NGB
2373           20170107           ICT                ICT            B.NGB
2374           20170107           ICT                ICT            B.NGB
2375           20170107           ICT                ICT            B.NGB
2376           20170107           ICT                ICT            B.NGB
2377           20170107           ICT                ICT            B.NGB
2378           20170107           ICT                ICT            B.NGB
2379           20170107           ICT                ICT            B.NGB
2380           20170107           ICT                ICT            B.NGB
2381           20170107           ICT                ICT            B.NGB
2382           20170107           ICT                ICT            B.NGB
2383           20170107           ICT                ICT            B.NGB
2384           20170107           ICT                ICT            B.NGB
2385           20170107           ICT                ICT            B.SHA
2386           20170107           ICT                ICT            B.SHA
2387           20170107           ICT                ICT            B.SHA
2388           20170107           ICT                ICT            B.SHA
2389           20170107           ICT                ICT            B.SHA
2390           20170107           ICT                ICT            B.SHA
2391           20170107           ICT                ICT            B.SHA
2392           20170107           ICT                ICT            B.SHA
2393           20170107           ICT                ICT            B.TAO
2394           20170107           ICT                ICT            B.TAO
2395           20170107           ICT                ICT            B.TAO
2396           20170107           ICT                ICT            B.TAO
2397           20170107           ICT                ICT            B.TAO
2398           20170107           ICT                ICT            B.TAO

     BPM Sales Ofce Cde BPM Local Region     ...      \
0                   FOC            B.XMN     ...
1                   ZZU            B.XMN     ...
2                   ZZU            B.XMN     ...
3                   ZZU            B.XMN     ...
4                   YIK            B.DLC     ...
5                   JKT            B.IDN     ...
6                   JKT            B.IDN     ...
7                   JKT            B.IDN     ...
8                   JKT            B.IDN     ...
9                   JKT            B.IDN     ...
10                  JKT            B.IDN     ...
11                  JKT            B.IDN     ...
12                  JKT            B.IDN     ...
13                  JKT            B.IDN     ...
14                  JKT            B.IDN     ...
15                  JKT            B.IDN     ...
16                  JKT            B.IDN     ...
17                  JKT            B.IDN     ...
18                  JED        B.Asia(W)     ...
19                  JED        B.Asia(W)     ...
20                  IST         C.Europe     ...
21                  IST         C.Europe     ...
22                  PIR         C.Europe     ...
23                  DLC            B.DLC     ...
24                  YIK            B.DLC     ...
25                  YIK            B.DLC     ...
26                  YIK            B.DLC     ...
27                  HQR            B.DLC     ...
28                  KHN            B.DLC     ...
29                  KHN            B.DLC     ...
...                 ...              ...     ...
2369                NGB            B.NGB     ...
2370                NGB            B.NGB     ...
2371                NGB            B.NGB     ...
2372                NGB            B.NGB     ...
2373                NGB            B.NGB     ...
2374                NGB            B.NGB     ...
2375                NGB            B.NGB     ...
2376                NGB            B.NGB     ...
2377                NGB            B.NGB     ...
2378                NGB            B.NGB     ...
2379                NGB            B.NGB     ...
2380                NGB            B.NGB     ...
2381                WNZ            B.NGB     ...
2382                YWZ            B.NGB     ...
2383                YWZ            B.NGB     ...
2384                YWZ            B.NGB     ...
2385                CGU            B.SHA     ...
2386                CGU            B.SHA     ...
2387                WUX            B.TAO     ...
2388                WUX            B.TAO     ...
2389                WUX            B.TAO     ...
2390                WUX            B.TAO     ...
2391                WUX            B.TAO     ...
2392                WUX            B.TAO     ...
2393                TAO            B.TAO     ...
2394                TAO            B.TAO     ...
2395                TAO            B.TAO     ...
2396                TAO            B.TAO     ...
2397                TAO            B.TAO     ...
2398                TAO            B.TAO     ...

                                     Booking Party Name Dest Region  \
0     Fujian Transmode International Forwarder Corpo...  B.China(S)
1      Xiamen Xing Sheng Yuan Logistics Company Limited  B.China(S)
2     Xiamen Jintongxing International Logistics Com...  B.China(S)
3      Xiamen Xing Sheng Yuan Logistics Company Limited  B.China(S)
4              Shanghai Yijia Logistics Limited Company       B.SHA
5                              Transworld GLS Indonesia       B.MYS
6                                       EQUATOR MARINDO       B.MYS
7                                       EQUATOR MARINDO       B.MYS
8                                       EQUATOR MARINDO       B.MYS
9                              Transworld GLS Indonesia       B.MYS
10                             Transworld GLS Indonesia       B.MYS
11                           Samudera Lautan Luas (SLL)       B.MYS
12                                         MTT SHIPPING       B.MYS
13                                         MTT SHIPPING       B.MYS
14                             Ganindo Marine Transport       B.MYS
15                                 Bahari Eka Nusantara       B.MYS
16                                 Bahari Eka Nusantara       B.MYS
17                        INFINITY LOGISTINDO INDONESIA       B.MYS
18                                           Future Key    C.Europe
19                       Al Karsf Shipping & Forwarding    C.Europe
20                              Mira Transport Services    C.Europe
21    Esna Uluslararasi Tasimacilik Brokerlik Hizmet...    C.Europe
22                               P.Koniakos And Company    C.Europe
23                     Cosfredl Development Zone Branch       B.WUH
24           Ying Kou Yong Quan Shi Ye You Xian Gong Si       B.WUH
25           Guangzhou Huayue Logistics Company Limited       B.WUH
26            Ying Kou Jia Na Logistics Company Limited       B.WUH
27    Yingkou Economic Development Zone Wanhong Logi...       B.WUH
28    Cosco Dalian International Freight Company Lim...       B.WUH
29    Cosco Dalian International Freight Company Lim...       B.WUH
...                                                 ...         ...
2369    China Shipping Logistics (East) Company Limited  B.China(S)
2370                  Ningbo Fulai Wuliu Youxian Gongsi  B.China(S)
2371                  Sinotrans Eastern Company Limited  B.China(S)
2372  Ningbo High-tech Zone Kun yuan Freight Forward...  B.China(S)
2373    China Shipping Logistics (East) Company Limited  B.China(S)
2374                  Ningbo Jinfu Wuliu Youxian Gongsi  B.China(S)
2375                  Sinotrans Eastern Company Limited  B.China(S)
2376                  Ningbo Fulai Wuliu Youxian Gongsi  B.China(S)
2377                  Ningbo Jinfu Wuliu Youxian Gongsi  B.China(S)
2378                  Ningbo Fulai Wuliu Youxian Gongsi  B.China(S)
2379                  Ningbo Jinfu Wuliu Youxian Gongsi  B.China(S)
2380                  Ningbo Fulai Wuliu Youxian Gongsi  B.China(S)
2381  Cosco Zhejiang International Freight Company L...  B.China(S)
2382  Cosco Ningbo International Freight Company Lim...  B.China(S)
2383  Cosco Ningbo International Freight Company Lim...  B.China(S)
2384  Cosco Ningbo International Freight Company Lim...  B.China(S)
2385  Jiangsu Lee and Man Paper Manufacturing Compan...  B.China(S)
2386  Jiangsu Lee and Man Paper Manufacturing Compan...  B.China(S)
2387  Cosco Jiangsu International Freight Company Li...  B.China(S)
2388  Cosco Jiangsu International Freight Company Li...  B.China(S)
2389  Cosco Jiangsu International Freight Company Li...  B.China(S)
2390  Cosco Jiangsu International Freight Company Li...  B.China(S)
2391  Cosco Jiangsu International Freight Company Li...  B.China(S)
2392  Cosco Jiangsu International Freight Company Li...  B.China(S)
2393  Qingdao Huagang Transportation International L...       B.XMN
2394      Qingdao Ruishengda Logistics Compangy Limited       B.XMN
2395    Qingdao Dongfanghaihang Freight Company Limited       B.XMN
2396          Worldex Logistics Qingdao Company Limited       B.XMN
2397  Liao Ning Zhong Shun International Container L...  B.China(S)
2398  Liao Ning Zhong Shun International Container L...  B.China(S)

     Booking Office  FOB IND  CNTR TYPE GRP  BPM Sales Country  \
0               FOC        0       GP_Group              China
1               ZZU        0       GP_Group              China
2               ZZU        0       GP_Group              China
3               ZZU        0       GP_Group              China
4               YIK        0       GP_Group              China
5               JKT        0       DG_Group          Indonesia
6               JKT        0       GP_Group          Indonesia
7               JKT        0       GP_Group          Indonesia
8               JKT        0       GP_Group          Indonesia
9               JKT        0       GP_Group          Indonesia
10              JKT        0       GP_Group          Indonesia
11              JKT        0       GP_Group          Indonesia
12              JKT        0       GP_Group          Indonesia
13              JKT        0       GP_Group          Indonesia
14              JKT        0       GP_Group          Indonesia
15              JKT        0       GP_Group          Indonesia
16              JKT        0       GP_Group          Indonesia
17              JKT        0       GP_Group          Indonesia
18              JED        0       GP_Group       Saudi Arabia
19              JED        0       GP_Group       Saudi Arabia
20              IST        0       GP_Group             Turkey
21              IST        0       GP_Group             Turkey
22              PIR        0       GP_Group             Greece
23              DLC        0       GP_Group              China
24              YIK        0       GP_Group              China
25              YIK        0       GP_Group              China
26              YIK        0       GP_Group              China
27              YIK        0       GP_Group       Head Quarter
28              CGQ        0       GP_Group              China
29              CGQ        0       GP_Group              China
...             ...      ...            ...                ...
2369            NGB        0       GP_Group              China
2370            NGB        0       GP_Group              China
2371            NGB        0       GP_Group              China
2372            NGB        0       GP_Group              China
2373            NGB        0       GP_Group              China
2374            NGB        0       GP_Group              China
2375            NGB        0       GP_Group              China
2376            NGB        0       GP_Group              China
2377            NGB        0       GP_Group              China
2378            NGB        0       GP_Group              China
2379            NGB        0       GP_Group              China
2380            NGB        0       GP_Group              China
2381            WNZ        0       GP_Group              China
2382            NGB        0       GP_Group              China
2383            NGB        0       GP_Group              China
2384            NGB        0       GP_Group              China
2385            CGU        0       GP_Group              China
2386            CGU        0       GP_Group              China
2387            YNT        0       GP_Group              China
2388            YNT        0       GP_Group              China
2389            YNT        0       GP_Group              China
2390            YNT        0       GP_Group              China
2391            YNT        0       GP_Group              China
2392            YNT        0       GP_Group              China
2393            TAO        0       GP_Group              China
2394            TAO        0       GP_Group              China
2395            TAO        0       GP_Group              China
2396            TAO        0       GP_Group              China
2397            YNT        0       RF_Group              China
2398            YNT        0       RF_Group              China

      F_POL_DEP_TIME_ID INLAND_CGO_ID C3 Adjustment Dest Office
0              20170101             1        278.22         ZUH
1              20170101             1         28.77         ZUH
2              20170101             1        108.79         ZUH
3              20170101             1         26.58         ZUH

In [70]:
data_order = data.sort_values('C3 Adjustment')
# print(data_order['C3 Adjustment'])
reset_index = data_order.reset_index(drop=True)
print(reset_index.loc[0:10])

    Reporting Week  Sail Year  Sail Month  F Pol Dep Time Id  \
0           201701       2017           1           20170101
1           201701       2017           1           20170101
2           201701       2017           1           20170101
3           201701       2017           1           20170101
4           201701       2017           1           20170101
5           201701       2017           1           20170101
6           201701       2017           1           20170101
7           201701       2017           1           20170101
8           201701       2017           1           20170101
9           201701       2017           1           20170101
10          201701       2017           1           20170101

    L Pod Arr Time Id  Primary Svvd Close Date Cgo Trade Cde  \
0            20170104               20170101.0           ICT
1            20170104               20170101.0           ICT
2            20170106               20170101.0           JKT
3            20170106               20170101.0           JKT
4            20170107               20170101.0           ICT
5            20170107               20170101.0           ICT
6            20170107               20170101.0           IAT
7            20170107               20170101.0           ICT
8            20170107               20170101.0           IAT
9            20170105               20170101.0           IAT
10           20170106               20170101.0           ICT

   Cgo Trade Lane Cde Shipment DIR BPM Sales Region            ...             \
0                 ICT            S            B.DLC            ...
1                 ICT            S            B.DLC            ...
2                 CNJ            E            B.TAO            ...
3                 CNJ            E            B.TAO            ...
4                 ICT            S            B.NGB            ...
5                 ICT            N            B.SHA            ...
6                 IAA            N       C.Asia(SE)            ...
7                 ICT            S            B.NGB            ...
8                 IAA            N       C.Asia(SE)            ...
9                 IAW            N         B.Taiwan            ...
10                ICT            S            B.NGB            ...

   GBL Grp Main Nme BPM Sales Country F_POL_DEP_TIME_ID INLAND_CGO_ID  \
0               NaN             China          20170101             0
1               NaN             China          20170101             0
2               NaN             China          20170101             0
3               NaN             China          20170101             0
4               NaN             China          20170101             1
5               NaN             China          20170101             1
6   Kiswire Sdn Bhd         Singapore          20170101             1
7               NaN             China          20170101             1
8   Kiswire Sdn Bhd         Singapore          20170101             1
9               NaN            Taiwan          20170101             0
10              NaN             China          20170101             1

   SC_COMMODITY_GROUP C3 Adjustment Dest Office Commodity Group         品名  \
0                 NaN     -13399.87         CAN             NaN        NaN
1                 NaN     -13399.87         CAN             NaN        NaN
2                 NaN      -3422.76         TYO             RFV  冷箱货（水果蔬菜）
3                 NaN      -1322.53         TYO             RFV  冷箱货（水果蔬菜）
4                 NaN      -1130.71         LSH             NaN        NaN
5                 NaN       -887.83         YIK             NaN        NaN
6                 NaN       -676.30         BKK             NaN        NaN
7                 NaN       -628.15         LSH             NaN        NaN
8                 NaN       -490.59         BKK             NaN        NaN
9                 NaN       -464.48         NGB             OTH         其他
10                NaN       -461.70         CAN             NaN        NaN

    Primary SVVD Season Type
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
5                       PEAK
6                       PEAK
7                        NaN
8                       PEAK
9                       PEAK
10                       NaN

[11 rows x 80 columns]

In [71]:
# This function returns the hundredth item from a series
def hundreth_row(column):
    # Extract the hundredth item
    hundredth_item = column.loc[99]
    return hundredth_item

# Return the hundredth item from each column
hundredth_row = data.apply(hundreth_row)
print(hundredth_row)

Reporting Week                                           201701
Sail Year                                                  2017
Sail Month                                                    1
F Pol Dep Time Id                                      20170101
L Pod Arr Time Id                                      20170103
Primary Svvd Close Date                             2.01701e+07
Cgo Trade Cde                                               IAT
Cgo Trade Lane Cde                                          IAA
Shipment DIR                                                  N
BPM Sales Region                                     C.Asia(SE)
BPM Sales Ofce Cde                                          JKT
BPM Local Region                                          B.IDN
Orig Ofce Cde                                               JKT
Primary Svvd Id                                      GMIR2H021N
F Base Pol Svvd                                      GMIR2H021N
L Base Pod Svvd                                      GMIR2H022S
F Pol Svvd                                           GMIR2H021N
L Pod Svvd                                           GMIR2H022S
Trckg Grp Ref Cde                                    7140669960
Bl Ref Cde                                           7140669960
Sc Num                                                      NaN
AGMT NUM                                          JKT10847001v1
Agreement Creator                                           NaN
Agreement Approver                                          NaN
TEU                                                           2
Freight Revenue                                           404.5
Orig City Nme                                           Jakarta
Orig State                                         Jakarta Raya
Orig Country Nme                                      Indonesia
Dest City Nme                                        Port Klang
                                           ...
BOUND                                                        IB
Contrib1                                                 189.43
Contrib2                                                 162.27
Contrib3                                                 159.91
Net Freight                                               404.5
Cust ID                                                 6119195
Cust Main Name              Globelink Sea And Freight Indonesia
SOC IND                                                       0
Intra river Ind                                               0
Trade Division                                     COSCON S.E.A
Booking Party Code                                   1114746000
Booking Party Name          Globelink Sea And Freight Indonesia
Dest Region                                               B.MYS
Booking Office                                              JKT
Account Scale                                               NaN
BCO_NVO                                                     NaN
Industry                                                    NaN
FOB IND                                                       0
CNTR TYPE GRP                                          GP_Group
Region GRP Main Nme                                         NaN
GBL Grp Main Nme                                            NaN
BPM Sales Country                                     Indonesia
F_POL_DEP_TIME_ID                                      20170101
INLAND_CGO_ID                                                 0
SC_COMMODITY_GROUP                                          NaN
C3 Adjustment                                            158.63
Dest Office                                                 KUL
Commodity Group                                             GMT
品名                                                      服装, 纺织品
Primary SVVD Season Type                                    NaN
Length: 80, dtype: object

In [72]:
def not_null_count(column):
    column_null = pandas.isnull(column)
    null = column[column_null]
    return len(null)

column_null_count = data.apply(not_null_count)
print(column_null_count)

Reporting Week                 0
Sail Year                      0
Sail Month                     0
F Pol Dep Time Id              0
L Pod Arr Time Id              0
Primary Svvd Close Date       15
Cgo Trade Cde                  0
Cgo Trade Lane Cde             0
Shipment DIR                   4
BPM Sales Region               0
BPM Sales Ofce Cde             0
BPM Local Region               0
Orig Ofce Cde                  0
Primary Svvd Id               15
F Base Pol Svvd               15
L Base Pod Svvd               15
F Pol Svvd                     0
L Pod Svvd                     0
Trckg Grp Ref Cde              0
Bl Ref Cde                     0
Sc Num                      2251
AGMT NUM                     149
Agreement Creator            547
Agreement Approver           547
TEU                            0
Freight Revenue                0
Orig City Nme                  0
Orig State                    16
Orig Country Nme               0
Dest City Nme                  0
                            ...
BOUND                          5
Contrib1                       0
Contrib2                       0
Contrib3                       0
Net Freight                    0
Cust ID                        0
Cust Main Name                 0
SOC IND                        0
Intra river Ind                0
Trade Division                 0
Booking Party Code             0
Booking Party Name             0
Dest Region                    0
Booking Office                 0
Account Scale               2224
BCO_NVO                      389
Industry                    1830
FOB IND                        0
CNTR TYPE GRP                  0
Region GRP Main Nme         2063
GBL Grp Main Nme            2064
BPM Sales Country              0
F_POL_DEP_TIME_ID              0
INLAND_CGO_ID                  0
SC_COMMODITY_GROUP          2251
C3 Adjustment                  0
Dest Office                    0
Commodity Group              844
品名                           844
Primary SVVD Season Type    1323
Length: 80, dtype: int64

In [77]:
def is_Pn(row):
    if row['C3 Adjustment'] > 0:
        return 'Positive Number'
    else:
        return 'Negitive Number'
sub = data.apply(is_Pn, axis=1)
print(sub)

0       Positive Number
1       Positive Number
2       Positive Number
3       Positive Number
4       Positive Number
5       Positive Number
6       Positive Number
7       Positive Number
8       Positive Number
9       Positive Number
10      Positive Number
11      Positive Number
12      Positive Number
13      Positive Number
14      Positive Number
15      Positive Number
16      Positive Number
17      Positive Number
18      Positive Number
19      Positive Number
20      Positive Number
21      Positive Number
22      Positive Number
23      Positive Number
24      Positive Number
25      Positive Number
26      Positive Number
27      Positive Number
28      Positive Number
29      Positive Number
             ...
2369    Positive Number
2370    Positive Number
2371    Negitive Number
2372    Positive Number
2373    Positive Number
2374    Positive Number
2375    Positive Number
2376    Positive Number
2377    Positive Number
2378    Positive Number
2379    Positive Number
2380    Positive Number
2381    Positive Number
2382    Positive Number
2383    Positive Number
2384    Positive Number
2385    Positive Number
2386    Positive Number
2387    Positive Number
2388    Positive Number
2389    Positive Number
2390    Positive Number
2391    Positive Number
2392    Positive Number
2393    Positive Number
2394    Positive Number
2395    Positive Number
2396    Positive Number
2397    Positive Number
2398    Positive Number
Length: 2399, dtype: object